[2022-11-02 16:50:35,435] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_inference_pipeline.encoding_categorical_variables manual__2022-11-02T16:50:29.124658+00:00 [queued]>
[2022-11-02 16:50:35,441] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_inference_pipeline.encoding_categorical_variables manual__2022-11-02T16:50:29.124658+00:00 [queued]>
[2022-11-02 16:50:35,441] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-11-02 16:50:35,441] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-11-02 16:50:35,442] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-11-02 16:50:35,453] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): encoding_categorical_variables> on 2022-11-02 16:50:29.124658+00:00
[2022-11-02 16:50:35,459] {standard_task_runner.py:52} INFO - Started process 10454 to run task
[2022-11-02 16:50:35,465] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Lead_scoring_inference_pipeline', 'encoding_categorical_variables', 'manual__2022-11-02T16:50:29.124658+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/Lead_scoring_inference_pipeline/.ipynb_checkpoints/lead_scoring_inference_pipeline-checkpoint.py', '--cfg-path', '/tmp/tmp2nr6cduu', '--error-file', '/tmp/tmpax23w43m']
[2022-11-02 16:50:35,466] {standard_task_runner.py:80} INFO - Job 39: Subtask encoding_categorical_variables
[2022-11-02 16:50:35,506] {task_command.py:371} INFO - Running <TaskInstance: Lead_scoring_inference_pipeline.encoding_categorical_variables manual__2022-11-02T16:50:29.124658+00:00 [running]> on host a3d1d2a51488
[2022-11-02 16:50:35,550] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Lead_scoring_inference_pipeline
AIRFLOW_CTX_TASK_ID=encoding_categorical_variables
AIRFLOW_CTX_EXECUTION_DATE=2022-11-02T16:50:29.124658+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-02T16:50:29.124658+00:00
[2022-11-02 16:50:35,551] {logging_mixin.py:115} INFO - Error while running encode_features : name 'DB_PATH' is not defined
[2022-11-02 16:50:35,551] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/dags/Lead_scoring_inference_pipeline/utils.py", line 99, in encode_features
    if connection:
UnboundLocalError: local variable 'connection' referenced before assignment
[2022-11-02 16:50:35,555] {taskinstance.py:1415} INFO - Marking task as UP_FOR_RETRY. dag_id=Lead_scoring_inference_pipeline, task_id=encoding_categorical_variables, execution_date=20221102T165029, start_date=20221102T165035, end_date=20221102T165035
[2022-11-02 16:50:35,562] {standard_task_runner.py:92} ERROR - Failed to execute job 39 for task encoding_categorical_variables (local variable 'connection' referenced before assignment; 10454)
[2022-11-02 16:50:35,593] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-11-02 16:50:35,624] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
