[2022-11-02 16:50:43,119] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_inference_pipeline.encoding_categorical_variables manual__2022-11-02T16:50:29.124658+00:00 [queued]>
[2022-11-02 16:50:43,124] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_inference_pipeline.encoding_categorical_variables manual__2022-11-02T16:50:29.124658+00:00 [queued]>
[2022-11-02 16:50:43,124] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-11-02 16:50:43,124] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-11-02 16:50:43,124] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-11-02 16:50:43,132] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): encoding_categorical_variables> on 2022-11-02 16:50:29.124658+00:00
[2022-11-02 16:50:43,138] {standard_task_runner.py:52} INFO - Started process 10492 to run task
[2022-11-02 16:50:43,144] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Lead_scoring_inference_pipeline', 'encoding_categorical_variables', 'manual__2022-11-02T16:50:29.124658+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/Lead_scoring_inference_pipeline/.ipynb_checkpoints/lead_scoring_inference_pipeline-checkpoint.py', '--cfg-path', '/tmp/tmpaezfxnsw', '--error-file', '/tmp/tmpoll3q8pr']
[2022-11-02 16:50:43,145] {standard_task_runner.py:80} INFO - Job 41: Subtask encoding_categorical_variables
[2022-11-02 16:50:43,180] {task_command.py:371} INFO - Running <TaskInstance: Lead_scoring_inference_pipeline.encoding_categorical_variables manual__2022-11-02T16:50:29.124658+00:00 [running]> on host a3d1d2a51488
[2022-11-02 16:50:43,220] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Lead_scoring_inference_pipeline
AIRFLOW_CTX_TASK_ID=encoding_categorical_variables
AIRFLOW_CTX_EXECUTION_DATE=2022-11-02T16:50:29.124658+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-02T16:50:29.124658+00:00
[2022-11-02 16:50:43,221] {logging_mixin.py:115} INFO - Error while running encode_features : name 'DB_PATH' is not defined
[2022-11-02 16:50:43,221] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/dags/Lead_scoring_inference_pipeline/utils.py", line 99, in encode_features
    if connection:
UnboundLocalError: local variable 'connection' referenced before assignment
[2022-11-02 16:50:43,223] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=Lead_scoring_inference_pipeline, task_id=encoding_categorical_variables, execution_date=20221102T165029, start_date=20221102T165043, end_date=20221102T165043
[2022-11-02 16:50:43,230] {standard_task_runner.py:92} ERROR - Failed to execute job 41 for task encoding_categorical_variables (local variable 'connection' referenced before assignment; 10492)
[2022-11-02 16:50:43,272] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-11-02 16:50:43,303] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
